# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-19 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_merge_20190814_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionflattened',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Created At'),
        ),
        migrations.AddField(
            model_name='discussionflattened',
            name='parent_entry_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Parent Discussion Entry Id'),
        ),
    ]
