# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-20 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20190819_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionCoherence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Table Id')),
                ('topic_id', models.BigIntegerField(verbose_name='Discussion Topic Id')),
                ('entry_id', models.BigIntegerField(blank=True, null=True, verbose_name='Discussion Entry Id')),
                ('coherence', models.FloatField(blank=True, null=True, verbose_name='Coherence')),
            ],
            options={
                'db_table': 'discussion_coherence',
            },
        ),
        migrations.AlterUniqueTogether(
            name='discussioncoherence',
            unique_together=set([('topic_id', 'entry_id')]),
        ),
    ]
