# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-29 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20190819_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Account Id')),
                ('canvas_id', models.BigIntegerField(verbose_name='Canvas Id')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('depth', models.IntegerField(verbose_name='Depth')),
                ('parent_account_id', models.BigIntegerField(verbose_name='Parent Account Id')),
                ('grandparent_account_id', models.BigIntegerField(verbose_name='Grandparent Account Id')),
                ('root_account_id', models.BigIntegerField(verbose_name='Root Account Id')),
                ('subaccount1_id', models.BigIntegerField(verbose_name='Subaccount 1 Id')),
                ('subaccount2_id', models.BigIntegerField(verbose_name='Subaccount 2 Id')),
                ('subaccount3_id', models.BigIntegerField(verbose_name='Subaccount 3 Id')),
                ('subaccount4_id', models.BigIntegerField(verbose_name='Subaccount 4 Id')),
                ('subaccount5_id', models.BigIntegerField(verbose_name='Subaccount 5 Id')),
                ('subaccount6_id', models.BigIntegerField(verbose_name='Subaccount 6 Id')),
                ('subaccount7_id', models.BigIntegerField(verbose_name='Subaccount 7 Id')),
                ('subaccount8_id', models.BigIntegerField(verbose_name='Subaccount 8 Id')),
                ('subaccount9_id', models.BigIntegerField(verbose_name='Subaccount 9 Id')),
                ('subaccount10_id', models.BigIntegerField(verbose_name='Subaccount 10 Id')),
                ('subaccount11_id', models.BigIntegerField(verbose_name='Subaccount 11 Id')),
                ('subaccount12_id', models.BigIntegerField(verbose_name='Subaccount 12 Id')),
                ('subaccount13_id', models.BigIntegerField(verbose_name='Subaccount 13 Id')),
                ('subaccount14_id', models.BigIntegerField(verbose_name='Subaccount 14 Id')),
                ('subaccount15_id', models.BigIntegerField(verbose_name='Subaccount 15 Id')),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
