# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-29 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='grandparent_account_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Grandparent Account Id'),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent_account_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Parent Account Id'),
        ),
        migrations.AlterField(
            model_name='account',
            name='root_account_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Root Account Id'),
        ),
        migrations.AlterField(
            model_name='account',
            name='subaccount10_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Subaccount 10 Id'),
        ),
        migrations.AlterField(
            model_name='account',
            name='subaccount11_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Subaccount 11 Id'),
        ),
        migrations.AlterField(
            model_name='account',
            name='subaccount12_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Subaccount 12 Id'),
        ),
        migrations.AlterField(
            model_name='account',
            name='subaccount13_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Subaccount 13 Id'),
        ),
        migrations.AlterField(
            model_name='account',
            name='subaccount14_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Subaccount 14 Id'),
        ),
        migrations.AlterField(
            model_name='account',
            name='subaccount15_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Subaccount 15 Id'),
        ),
        migrations.AlterField(
            model_name='account',
            name='subaccount1_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Subaccount 1 Id'),
        ),
        migrations.AlterField(
            model_name='account',
            name='subaccount2_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Subaccount 2 Id'),
        ),
        migrations.AlterField(
            model_name='account',
            name='subaccount3_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Subaccount 3 Id'),
        ),
        migrations.AlterField(
            model_name='account',
            name='subaccount4_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Subaccount 4 Id'),
        ),
        migrations.AlterField(
            model_name='account',
            name='subaccount5_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Subaccount 5 Id'),
        ),
        migrations.AlterField(
            model_name='account',
            name='subaccount6_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Subaccount 6 Id'),
        ),
        migrations.AlterField(
            model_name='account',
            name='subaccount7_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Subaccount 7 Id'),
        ),
        migrations.AlterField(
            model_name='account',
            name='subaccount8_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Subaccount 8 Id'),
        ),
        migrations.AlterField(
            model_name='account',
            name='subaccount9_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Subaccount 9 Id'),
        ),
    ]
